### PR TITLE
Add multiple ruby versions

### PR DESCRIPTION
**Pull request by paulRbr**
This is a draft version to be able to install multiple rubies at once on a machine.

Feel free to review and comment. I would be happy to help on #35

### CODE REVIEW

**Comment by zzet** [comment]
@paulRbr thx for this PR. I like this implementation.

@blackjid, @Silox, @jufemaiz It's resolve your issues?

**Comment by paulRbr** [comment]
There are a few things we could improve:
- remove the mandatory `default_ruby` var if there is only one ruby in the `rubies` array
- fix the tests. Actually I don't really get why they fail?

**Comment by blackjid** [comment]
LGTM

**Comment by jufemaiz** [comment]
Looks good to me too.

**Comment by arthurnn** [comment]
lovely. Thanks ❤️

**Pull request merged**
